import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.work': 'Work',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'hero.title': 'Design. Motion. Storytelling.',
    'hero.tagline': 'Crafting meaningful experiences through UX design, motion graphics, and cinematic narratives.',
    'hero.scroll': 'Scroll to explore',
    'about.title': 'About Me',
    'about.bio1': 'I\'m Héctor Granero, a multidisciplinary designer and filmmaker with a passion for blending digital innovation with cinematic storytelling.',
    'about.bio2': 'With years of experience in UX design, motion graphics, and film direction, I create experiences that resonate emotionally and function beautifully.',
    'about.bio3': 'My approach combines strategic thinking, visual aesthetics, and narrative depth to craft work that stands out in the digital landscape.',
    'projects.title': 'Selected Work',
    'projects.view': 'View Project',
    'services.title': 'Services',
    'services.ux.title': 'UX Design',
    'services.ux.description': 'User-centered design solutions that combine research, strategy, and interface design to create intuitive digital experiences.',
    'services.motion.title': 'Motion Design',
    'services.motion.description': 'Dynamic visual storytelling through animation, bringing brands and ideas to life with compelling motion graphics.',
    'services.film.title': 'Film Direction',
    'services.film.description': 'Cinematic narratives that capture emotion and meaning, from concept development to final production.',
    'contact.title': 'Let\'s Create Something Meaningful',
    'contact.intro': 'Whether it\'s a new project, collaboration, or just a conversation about design and storytelling, I\'d love to hear from you.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'footer.rights': 'All rights reserved.',
    'project.concept': 'Concept',
    'project.role': 'Role',
    'project.tools': 'Tools',
    'project.process': 'Process',
    'project.results': 'Results',
    'project.back': 'Back to Work',
    // CV Section
    'cv.header.name': 'Héctor Granero',
    'cv.header.title': 'Senior UX Designer | Design Systems & B2B Platforms',
    'cv.header.tagline': 'Designing scalable UX for complex platforms — with clarity, systems thinking, and consistency.',
    'cv.bio.intro': 'I specialize in creating intuitive, scalable design systems for B2B platforms and enterprise applications. With over 10 years of experience across fintech, SaaS, and digital innovation, I bridge user needs with business goals through research-driven design, cross-functional collaboration, and a strong focus on consistency and usability.',
    'cv.experience.title': 'Experience',
    'cv.experience.terms.role': 'Lead UX Designer',
    'cv.experience.terms.period': 'Dec 2022 – Present',
    'cv.experience.terms.location': 'Remote',
    'cv.experience.terms.description': 'Lead UX efforts for a B2B embedded finance platform enabling marketplaces and PSPs to offer flexible payment terms.',
    'cv.experience.terms.impact1': 'End-to-end design of onboarding and transaction flows',
    'cv.experience.terms.impact2': 'Scalable design system for white-label integration',
    'cv.experience.growkap.role': 'Design Lead',
    'cv.experience.growkap.period': 'Mar 2024 – Present',
    'cv.experience.growkap.location': 'Remote',
    'cv.experience.growkap.description': 'Design lead for a fintech solution offering purchase order financing to growing SMEs.',
    'cv.experience.growkap.impact1': 'Product definition and UI/UX consistency',
    'cv.experience.growkap.impact2': 'Building user trust through clear, intuitive interfaces',
    'cv.experience.area42.role': 'UX/UI Designer',
    'cv.experience.area42.period': 'Nov 2021 – Present',
    'cv.experience.area42.location': 'Remote',
    'cv.experience.area42.description': 'Support innovation products within AREA42, the venture builder of Credendo Group.',
    'cv.experience.area42.impact1': 'UX and visual design of early-stage B2B trade tech solutions',
    'cv.experience.area42.impact2': 'MVPs, component libraries, and brand alignment',
    'cv.experience.sap.role': 'UX Designer',
    'cv.experience.sap.period': 'Mar 2013 – Mar 2020',
    'cv.experience.sap.location': 'Paris, France',
    'cv.experience.sap.description': 'Collaborated within SAP\'s Global Design Team on the Fiori Design System.',
    'cv.experience.sap.impact1': 'Visual and interaction design of enterprise applications',
    'cv.experience.sap.impact2': 'UI consistency, component libraries, and CSS/HTML5 implementation',
    'cv.leadership.title': 'Leadership',
    'cv.leadership.souris.role': 'Co-founder & Creative Director',
    'cv.leadership.souris.company': 'Souristoutirabien',
    'cv.leadership.souris.period': 'Since 2018',
    'cv.leadership.souris.location': 'Strasbourg, France',
    'cv.leadership.souris.description': 'Founded a studio combining UX design and filmmaking. Led digital and audiovisual projects, balancing usability, visual design, and storytelling for brands and institutions.',
    'cv.skills.title': 'Skills & Expertise',
    'cv.skills.ux.title': 'UX Design & Research',
    'cv.skills.ux.items': 'User Research,Interaction Design,Usability Testing,Information Architecture',
    'cv.skills.systems.title': 'Design Systems & Product',
    'cv.skills.systems.items': 'Component Libraries,Design Tokens,Product Consistency,Design Ops',
    'cv.skills.research.title': 'Prototyping & Collaboration',
    'cv.skills.research.items': 'Rapid Prototyping,Cross-functional Teams,Agile Workflows,Stakeholder Management',
    'cv.skills.tools.title': 'Tools & Technologies',
    'cv.skills.tools.items': 'Figma,Sketch,Adobe Suite,JIRA,Confluence,Miro',
    'cv.education.title': 'Education',
    'cv.education.hci.degree': 'Master of Science in Human-Computer Interaction',
    'cv.education.hci.institution': 'IP Formation, Paris',
    'cv.education.hci.period': '2013 – 2014',
    'cv.education.finarts.degree': 'Bachelor of Fine Arts & Master\'s in Artistic Production',
    'cv.education.finarts.institution': 'Universitat Politècnica de València',
    'cv.education.finarts.period': '2005 – 2012',
    'cv.languages.title': 'Languages',
    'cv.languages.spanish': 'Spanish',
    'cv.languages.catalan': 'Catalan',
    'cv.languages.french': 'French',
    'cv.languages.english': 'English',
    'cv.languages.italian': 'Italian',
    'cv.languages.native': 'Native',
    'cv.languages.fluent': 'Fluent',
    'cv.languages.working': 'Working',
    'cv.cta.viewWork': 'View Work',
    'cv.cta.downloadCV': 'Download CV',
    'cv.footer.contact': 'Get in touch:',
  },
  fr: {
    'nav.work': 'Travaux',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'hero.title': 'Design. Motion. Storytelling.',
    'hero.tagline': 'Créer des expériences significatives à travers le design UX, le motion graphics et les récits cinématographiques.',
    'hero.scroll': 'Défiler pour explorer',
    'about.title': 'À propos de moi',
    'about.bio1': 'Je suis Héctor Granero, designer multidisciplinaire et cinéaste passionné par le mélange de l\'innovation digitale et de la narration cinématographique.',
    'about.bio2': 'Avec des années d\'expérience en design UX, motion graphics et réalisation, je crée des expériences qui résonnent émotionnellement et fonctionnent magnifiquement.',
    'about.bio3': 'Mon approche combine réflexion stratégique, esthétique visuelle et profondeur narrative pour créer un travail qui se démarque dans le paysage digital.',
    'projects.title': 'Travaux sélectionnés',
    'projects.view': 'Voir le projet',
    'services.title': 'Services',
    'services.ux.title': 'Design UX',
    'services.ux.description': 'Solutions de design centrées sur l\'utilisateur qui combinent recherche, stratégie et design d\'interface pour créer des expériences digitales intuitives.',
    'services.motion.title': 'Motion Design',
    'services.motion.description': 'Storytelling visuel dynamique par l\'animation, donnant vie aux marques et aux idées avec des motion graphics convaincants.',
    'services.film.title': 'Réalisation',
    'services.film.description': 'Récits cinématographiques qui capturent émotion et sens, du développement du concept à la production finale.',
    'contact.title': 'Créons quelque chose de significatif',
    'contact.intro': 'Que ce soit un nouveau projet, une collaboration ou simplement une conversation sur le design et le storytelling, j\'aimerais vous entendre.',
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Envoyer',
    'footer.rights': 'Tous droits réservés.',
    'project.concept': 'Concept',
    'project.role': 'Rôle',
    'project.tools': 'Outils',
    'project.process': 'Processus',
    'project.results': 'Résultats',
    'project.back': 'Retour aux travaux',
    // CV Section
    'cv.header.name': 'Héctor Granero',
    'cv.header.title': 'Designer UX Senior | Design Systems & Plateformes B2B',
    'cv.header.tagline': 'Concevoir des UX évolutives pour plateformes complexes — avec clarté, pensée systémique et cohérence.',
    'cv.bio.intro': 'Je me spécialise dans la création de design systems intuitifs et évolutifs pour plateformes B2B et applications d\'entreprise. Avec plus de 10 ans d\'expérience dans la fintech, le SaaS et l\'innovation numérique, je fais le pont entre besoins utilisateurs et objectifs business à travers un design basé sur la recherche, la collaboration interfonctionnelle et un fort accent sur la cohérence et l\'utilisabilité.',
    'cv.experience.title': 'Expérience',
    'cv.experience.terms.role': 'Lead Designer UX',
    'cv.experience.terms.period': 'Déc 2022 – Présent',
    'cv.experience.terms.location': 'À distance',
    'cv.experience.terms.description': 'Lead UX pour une plateforme B2B de finance embarquée permettant aux marketplaces et PSP d\'offrir des conditions de paiement flexibles.',
    'cv.experience.terms.impact1': 'Conception end-to-end des flux d\'onboarding et de transaction',
    'cv.experience.terms.impact2': 'Design system évolutif pour intégration white-label',
    'cv.experience.growkap.role': 'Lead Designer',
    'cv.experience.growkap.period': 'Mar 2024 – Présent',
    'cv.experience.growkap.location': 'À distance',
    'cv.experience.growkap.description': 'Lead design pour une solution fintech offrant du financement de bons de commande aux PME en croissance.',
    'cv.experience.growkap.impact1': 'Définition produit et cohérence UI/UX',
    'cv.experience.growkap.impact2': 'Créer la confiance utilisateur via des interfaces claires et intuitives',
    'cv.experience.area42.role': 'Designer UX/UI',
    'cv.experience.area42.period': 'Nov 2021 – Présent',
    'cv.experience.area42.location': 'À distance',
    'cv.experience.area42.description': 'Support des produits d\'innovation au sein d\'AREA42, le venture builder du Groupe Credendo.',
    'cv.experience.area42.impact1': 'Design UX et visuel de solutions trade tech B2B early-stage',
    'cv.experience.area42.impact2': 'MVPs, bibliothèques de composants et alignement de marque',
    'cv.experience.sap.role': 'Designer UX',
    'cv.experience.sap.period': 'Mar 2013 – Mar 2020',
    'cv.experience.sap.location': 'Paris, France',
    'cv.experience.sap.description': 'Collaboration au sein de l\'équipe design globale SAP sur le Fiori Design System.',
    'cv.experience.sap.impact1': 'Design visuel et d\'interaction d\'applications d\'entreprise',
    'cv.experience.sap.impact2': 'Cohérence UI, bibliothèques de composants et implémentation CSS/HTML5',
    'cv.leadership.title': 'Leadership',
    'cv.leadership.souris.role': 'Co-fondateur & Directeur Créatif',
    'cv.leadership.souris.company': 'Souristoutirabien',
    'cv.leadership.souris.period': 'Depuis 2018',
    'cv.leadership.souris.location': 'Strasbourg, France',
    'cv.leadership.souris.description': 'Fondé un studio combinant design UX et réalisation. Direction de projets digitaux et audiovisuels, équilibrant utilisabilité, design visuel et storytelling pour marques et institutions.',
    'cv.skills.title': 'Compétences & Expertise',
    'cv.skills.ux.title': 'Design & Recherche UX',
    'cv.skills.ux.items': 'Recherche Utilisateur,Design d\'Interaction,Tests d\'Utilisabilité,Architecture de l\'Information',
    'cv.skills.systems.title': 'Design Systems & Produit',
    'cv.skills.systems.items': 'Bibliothèques de Composants,Design Tokens,Cohérence Produit,Design Ops',
    'cv.skills.research.title': 'Prototypage & Collaboration',
    'cv.skills.research.items': 'Prototypage Rapide,Équipes Interfonctionnelles,Workflows Agiles,Gestion des Parties Prenantes',
    'cv.skills.tools.title': 'Outils & Technologies',
    'cv.skills.tools.items': 'Figma,Sketch,Adobe Suite,JIRA,Confluence,Miro',
    'cv.education.title': 'Formation',
    'cv.education.hci.degree': 'Master of Science en Interaction Homme-Machine',
    'cv.education.hci.institution': 'IP Formation, Paris',
    'cv.education.hci.period': '2013 – 2014',
    'cv.education.finarts.degree': 'Licence en Beaux-Arts & Master en Production Artistique',
    'cv.education.finarts.institution': 'Universitat Politècnica de València',
    'cv.education.finarts.period': '2005 – 2012',
    'cv.languages.title': 'Langues',
    'cv.languages.spanish': 'Espagnol',
    'cv.languages.catalan': 'Catalan',
    'cv.languages.french': 'Français',
    'cv.languages.english': 'Anglais',
    'cv.languages.italian': 'Italien',
    'cv.languages.native': 'Natif',
    'cv.languages.fluent': 'Courant',
    'cv.languages.working': 'Professionnel',
    'cv.cta.viewWork': 'Voir les travaux',
    'cv.cta.downloadCV': 'Télécharger CV',
    'cv.footer.contact': 'Me contacter :',
  },
  es: {
    'nav.work': 'Trabajo',
    'nav.about': 'Sobre mí',
    'nav.services': 'Servicios',
    'nav.contact': 'Contacto',
    'hero.title': 'Design. Motion. Storytelling.',
    'hero.tagline': 'Creando experiencias significativas a través del diseño UX, motion graphics y narrativas cinematográficas.',
    'hero.scroll': 'Desplázate para explorar',
    'about.title': 'Sobre mí',
    'about.bio1': 'Soy Héctor Granero, diseñador multidisciplinario y cineasta con pasión por fusionar la innovación digital con la narrativa cinematográfica.',
    'about.bio2': 'Con años de experiencia en diseño UX, motion graphics y dirección de cine, creo experiencias que resuenan emocionalmente y funcionan bellamente.',
    'about.bio3': 'Mi enfoque combina pensamiento estratégico, estética visual y profundidad narrativa para crear trabajo que destaca en el panorama digital.',
    'projects.title': 'Trabajo seleccionado',
    'projects.view': 'Ver proyecto',
    'services.title': 'Servicios',
    'services.ux.title': 'Diseño UX',
    'services.ux.description': 'Soluciones de diseño centradas en el usuario que combinan investigación, estrategia y diseño de interfaz para crear experiencias digitales intuitivas.',
    'services.motion.title': 'Motion Design',
    'services.motion.description': 'Storytelling visual dinámico a través de animación, dando vida a marcas e ideas con motion graphics cautivadores.',
    'services.film.title': 'Dirección de Cine',
    'services.film.description': 'Narrativas cinematográficas que capturan emoción y significado, desde el desarrollo del concepto hasta la producción final.',
    'contact.title': 'Creemos algo significativo',
    'contact.intro': 'Ya sea un nuevo proyecto, colaboración o simplemente una conversación sobre diseño y storytelling, me encantaría saber de ti.',
    'contact.name': 'Nombre',
    'contact.email': 'Email',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar mensaje',
    'footer.rights': 'Todos los derechos reservados.',
    'project.concept': 'Concepto',
    'project.role': 'Rol',
    'project.tools': 'Herramientas',
    'project.process': 'Proceso',
    'project.results': 'Resultados',
    'project.back': 'Volver al trabajo',
    // CV Section
    'cv.header.name': 'Héctor Granero',
    'cv.header.title': 'Diseñador UX Senior | Design Systems & Plataformas B2B',
    'cv.header.tagline': 'Diseñando UX escalable para plataformas complejas — con claridad, pensamiento sistémico y consistencia.',
    'cv.bio.intro': 'Me especializo en crear design systems intuitivos y escalables para plataformas B2B y aplicaciones empresariales. Con más de 10 años de experiencia en fintech, SaaS e innovación digital, conecto necesidades de usuarios con objetivos de negocio a través de diseño basado en investigación, colaboración interfuncional y un fuerte enfoque en consistencia y usabilidad.',
    'cv.experience.title': 'Experiencia',
    'cv.experience.terms.role': 'Lead Diseñador UX',
    'cv.experience.terms.period': 'Dic 2022 – Presente',
    'cv.experience.terms.location': 'Remoto',
    'cv.experience.terms.description': 'Lead UX para una plataforma B2B de finanzas embebidas que permite a marketplaces y PSPs ofrecer condiciones de pago flexibles.',
    'cv.experience.terms.impact1': 'Diseño end-to-end de flujos de onboarding y transacciones',
    'cv.experience.terms.impact2': 'Design system escalable para integración white-label',
    'cv.experience.growkap.role': 'Lead Diseñador',
    'cv.experience.growkap.period': 'Mar 2024 – Presente',
    'cv.experience.growkap.location': 'Remoto',
    'cv.experience.growkap.description': 'Lead de diseño para una solución fintech que ofrece financiación de órdenes de compra a PYMEs en crecimiento.',
    'cv.experience.growkap.impact1': 'Definición de producto y consistencia UI/UX',
    'cv.experience.growkap.impact2': 'Construir confianza del usuario mediante interfaces claras e intuitivas',
    'cv.experience.area42.role': 'Diseñador UX/UI',
    'cv.experience.area42.period': 'Nov 2021 – Presente',
    'cv.experience.area42.location': 'Remoto',
    'cv.experience.area42.description': 'Apoyo a productos de innovación dentro de AREA42, el venture builder del Grupo Credendo.',
    'cv.experience.area42.impact1': 'Diseño UX y visual de soluciones trade tech B2B en fase temprana',
    'cv.experience.area42.impact2': 'MVPs, bibliotecas de componentes y alineación de marca',
    'cv.experience.sap.role': 'Diseñador UX',
    'cv.experience.sap.period': 'Mar 2013 – Mar 2020',
    'cv.experience.sap.location': 'París, Francia',
    'cv.experience.sap.description': 'Colaboración en el equipo de diseño global de SAP en el Fiori Design System.',
    'cv.experience.sap.impact1': 'Diseño visual y de interacción de aplicaciones empresariales',
    'cv.experience.sap.impact2': 'Consistencia UI, bibliotecas de componentes e implementación CSS/HTML5',
    'cv.leadership.title': 'Liderazgo',
    'cv.leadership.souris.role': 'Co-fundador & Director Creativo',
    'cv.leadership.souris.company': 'Souristoutirabien',
    'cv.leadership.souris.period': 'Desde 2018',
    'cv.leadership.souris.location': 'Estrasburgo, Francia',
    'cv.leadership.souris.description': 'Fundé un estudio que combina diseño UX y realización cinematográfica. Lideré proyectos digitales y audiovisuales, equilibrando usabilidad, diseño visual y storytelling para marcas e instituciones.',
    'cv.skills.title': 'Habilidades & Experiencia',
    'cv.skills.ux.title': 'Diseño & Investigación UX',
    'cv.skills.ux.items': 'Investigación de Usuario,Diseño de Interacción,Pruebas de Usabilidad,Arquitectura de Información',
    'cv.skills.systems.title': 'Design Systems & Producto',
    'cv.skills.systems.items': 'Bibliotecas de Componentes,Design Tokens,Consistencia de Producto,Design Ops',
    'cv.skills.research.title': 'Prototipado & Colaboración',
    'cv.skills.research.items': 'Prototipado Rápido,Equipos Interfuncionales,Flujos Ágiles,Gestión de Stakeholders',
    'cv.skills.tools.title': 'Herramientas & Tecnologías',
    'cv.skills.tools.items': 'Figma,Sketch,Adobe Suite,JIRA,Confluence,Miro',
    'cv.education.title': 'Formación',
    'cv.education.hci.degree': 'Master of Science en Interacción Humano-Computadora',
    'cv.education.hci.institution': 'IP Formation, París',
    'cv.education.hci.period': '2013 – 2014',
    'cv.education.finarts.degree': 'Licenciatura en Bellas Artes & Máster en Producción Artística',
    'cv.education.finarts.institution': 'Universitat Politècnica de València',
    'cv.education.finarts.period': '2005 – 2012',
    'cv.languages.title': 'Idiomas',
    'cv.languages.spanish': 'Español',
    'cv.languages.catalan': 'Catalán',
    'cv.languages.french': 'Francés',
    'cv.languages.english': 'Inglés',
    'cv.languages.italian': 'Italiano',
    'cv.languages.native': 'Nativo',
    'cv.languages.fluent': 'Fluido',
    'cv.languages.working': 'Profesional',
    'cv.cta.viewWork': 'Ver trabajo',
    'cv.cta.downloadCV': 'Descargar CV',
    'cv.footer.contact': 'Contacto:',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
